alias gg='git gui &'
alias ggg='gitk &'
alias gitchanges='git log -p --'
alias gitundo='git reset HEAD~'
alias gitmergetrial='git --no-commit --no-ff'
alias gitbranchcleanup='git_remove_orphan_branches.sh'
alias gitp='lint && git push'
alias gitmessages='git log | grep eang -A 7 -B 2 | more'
alias gitclean='git gc && git prune && git remote prune origin'

alias triggerbuild='git commit --allow-empty -m "Trigger notification" && git push'
alias gitmergetrial='git --no-commit --no-ff'

alias gosources='cd ~/sources'
alias govagrant='cd ~/vagrant'

export VISUAL=vi
export EDITOR="$VISUAL"
