alias gg='git gui &'
alias ggg='gitk &'
alias gitchanges='git log -p --'
alias gitundo='git reset HEAD~'

alias gosources='cd ~/sources'
alias govagrant='cd ~/vagrant'

export VISUAL=vi
export EDITOR="$VISUAL"
